version: "3.8"
services:
  api:
    build: ./app3
    container_name: ap3_c
    ports:
      - '4000:4000'
    volumes:
      - ./app3:/app
      - /app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_c
    ports:
      - '3000:3000'
    stdin_open: true